pipeline {
    agent any

    environment {
        IMAGE_NAME = "monaahmed/backend"
        IMAGE_TAG  = "v${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'jenkin_git_pipeline',
                    url: 'https://github.com/monaahmed92/mona_deployment_project.git'
            }
        }

        stage('Build Docker Image') {
           steps {
                dir('backend') {
                    bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
                }
            }
        }


        stage('Push Image') {
           steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    bat "docker login -u %DOCKER_USER% -p %DOCKER_PASS%"
                    bat "docker push %IMAGE_NAME%:latest"
                }
    }
}


    post {
        success {
            echo "✅ Backend image pushed to Docker Hub: %IMAGE_NAME%:latest"
        }
        always {
            cleanWs()
        }
    }
}
