// pipeline {
//   agent any

//   environment {
//     AWS_DEFAULT_REGION = "us-east-1"
//     TF_IN_AUTOMATION   = "true"
//   }

//   stages {

//     stage('Checkout') {
//       steps {
//         checkout scm
//       }
//     }
//     stage('Terraform Check') {
//      steps {
//          bat 'terraform --version'
//         }
//      }

//     stage('Terraform Init') {
//       steps {
//         withCredentials([
//           [$class: 'AmazonWebServicesCredentialsBinding',
//            credentialsId: 'aws-credentials']
//         ]) {
//           dir('terraform') {
//             bat '''
//               terraform --version
//               terraform init -upgrade
//             '''
//           }
//         }
//       }
//     }
//     stage('Terraform Validate') {
//       steps {
//         dir('terraform') {
//           bat '''
//             terraform validate
//           '''
//         }
//       }
//     }
//     stage('Terraform Plan') {
//       steps {
//         withCredentials([
//           [$class: 'AmazonWebServicesCredentialsBinding',
//            credentialsId: 'aws-credentials']
//         ]) {
//           dir('terraform') {
//             bat '''
//               terraform plan -out=tfplan
//             '''
//           }
//         }
//       }
//     }
//     stage('Approval') {
//       steps {
//         input message: 'Apply Terraform changes to AWS?', ok: 'Apply'
//       }
//     }

//     stage('Terraform Apply') {
//       steps {
//         withCredentials([
//           [$class: 'AmazonWebServicesCredentialsBinding',
//            credentialsId: 'aws-credentials']
//         ]) {
//           dir('terraform') {
//             bat '''
//               terraform apply -auto-approve tfplan
//             '''
//           }
//         }
//       }
//     }
//   }

//   post {
//     success {
//       echo 'Terraform infrastructure deployed successfully.'
//     }
//     failure {
//       echo 'Terraform deployment failed.'
//     }
//   }
// }

pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = "us-east-1"
    TF_IN_AUTOMATION   = "true"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-credentials']
        ]) {
          dir('terraform') {
            bat '''
              del .terraform.lock.hcl
              terraform --version
              terraform init -upgrade
              terraform providers
            '''
          }
        }
      }
    }

    stage('Terraform Validate') {
      steps {
        dir('terraform') {
          bat 'terraform validate'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-credentials']
        ]) {
          dir('terraform') {
            bat 'terraform plan -out=tfplan'
          }
        }
      }
    }

    stage('Approval') {
      steps {
        input message: 'Apply Terraform changes to AWS?', ok: 'Apply'
      }
    }

    stage('Terraform Apply') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-credentials']
        ]) {
          dir('terraform') {
            bat 'terraform apply tfplan'
          }
        }
      }
    }

//     stage('Terraform Destroy') {
//   steps {
//     input message: 'WARNING: This will DESTROY all Terraform-managed infrastructure. Continue?',
//           ok: 'Destroy'

//     withCredentials([
//       [$class: 'AmazonWebServicesCredentialsBinding',
//        credentialsId: 'aws-credentials']
//     ]) {
//       dir('terraform') {
//         bat 'terraform destroy -auto-approve'
//       }
//     }
//   }
// }
  }

  post {
    success {
      echo 'Terraform infrastructure deployed successfully.'
    }
    failure {
      echo 'Terraform deployment failed.'
    }
  }
}

